/**
 * Données initiales complètes pour la page À Propos d'APTIC-R
 * Permet de seeder la base de données avec 100% de complétude en FR, EN et DE.
 */

export const INITIAL_ABOUT_SETTINGS: Record<string, string> = {
  // ── Statuts de publication explicites ──
  about_published_fr: "PUBLISHED",
  about_published_en: "PUBLISHED",
  about_published_de: "PUBLISHED",

  // ── Valeurs partagées ──
  about_story_image: "/photo-recit-documentaire.jpg",
  about_step1_year: "2018",
  about_step2_year: "2020",
  about_stat1_val: "5+",
  about_stat2_val: "3 200+",
  about_stat3_val: "14",
  about_stat4_val: "100%",

  // ── FRANÇAIS (100% complet) ──
  about_eyebrow_fr: "À PROPOS D'APTIC-R",
  about_title_fr: "Bâtir des ponts numériques durables\nau cœur du milieu rural.",
  about_subtitle_fr: "Depuis sa fondation à Agbélouvé, APTIC-R œuvre pour que la révolution numérique et technologique ne laisse aucun village, aucune femme et aucun jeune de côté.",
  about_story_eyebrow_fr: "NOTRE HISTOIRE",
  about_story_headline_fr: "Une initiative née du terrain, pour combler la fracture numérique rurale.",
  about_story_p1_fr: "En 2018, au cœur du canton d'Agbélouvé (préfecture du Zio, Togo), un constat s'impose avec acuité : alors que le monde s'accélère au rythme de l'intelligence artificielle et du numérique, les communautés villageoises restent privées d'infrastructures informatiques, de connexion stable et de formation technologique adaptée.",
  about_story_p2_fr: "Face au risque d'accroissement des inégalités territoriales et de marginalisation de la jeunesse rurale, un collectif d'ingénieurs, d'éducateurs et d'acteurs communautaires togolais décide d'agir. C'est ainsi que naît APTIC-R (Association Pour la Promotion des Technologies de l'Information et de la Communication en Milieu Rural).",
  about_story_p3_fr: "En implantant des tiers-lieux d'apprentissage équipés de matériel reconditionné et alimentés à l'énergie solaire, APTIC-R a transformé Agbélouvé en un laboratoire vivant de l'innovation rurale frugale et de l'artisanat connecté.",
  about_story_image_alt_fr: "Action de terrain APTIC-R à Agbélouvé, formation communautaire aux outils numériques",
  about_story_location_tag_fr: "Ancrage communautaire",
  about_story_location_fr: "Agbélouvé, Région Maritime",
  about_step1_label_fr: "Création à Agbélouvé",
  about_step2_label_fr: "Formalisation officielle",
  about_step3_year_fr: "Aujourd'hui",
  about_step3_label_fr: "Déploiement & Impact",
  about_pillars_eyebrow_fr: "CADRE D'INTERVENTION",
  about_pillars_title_fr: "Mission, Vision & Philosophie",
  about_mission_title_fr: "NOTRE MISSION",
  about_mission_desc_fr: "Démocratiser l'apprentissage technologique et les solutions numériques utiles dans les zones rurales et périurbaines du Togo à travers la formation continue, l'expérimentation concrète et le transfert durable de compétences.",
  about_vision_title_fr: "NOTRE VISION",
  about_vision_desc_fr: "Un milieu rural togolais et africain émancipé, où les technologies libres et les solutions low-tech renforcent durablement la souveraineté alimentaire, économique et civique des communautés locales.",
  about_philosophy_title_fr: "NOTRE PHILOSOPHIE",
  about_philosophy_desc_fr: "Le numérique sobre et adapté. Nous refusons la technologie superflue : chaque outil déployé doit être réparable localement, sobre en énergie, accessible à tous et directement utile aux besoins du village.",
  about_stat1_lbl_fr: "Années d'action sur le terrain",
  about_stat2_lbl_fr: "Enfants, jeunes et artisans formés",
  about_stat3_lbl_fr: "Établissements scolaires partenaires",
  about_stat4_lbl_fr: "Projets co-conçus localement",
  about_values_eyebrow_fr: "PRINCIPES FONDAMENTAUX",
  about_values_title_fr: "Nos 5 valeurs cardinales",
  about_values_subtitle_fr: "Des règles intangibles qui guident chacune de nos actions et collaborations.",
  about_val1_title_fr: "Ancrage communautaire",
  about_val1_desc_fr: "Rien ne se fait sans l'accord, la participation active et la co-responsabilité des chefs traditionnels, des associations locales et des familles villageoises.",
  about_val2_title_fr: "Sobriété numérique & Low-Tech",
  about_val2_desc_fr: "Privilégier le matériel reconditionné, l'énergie solaire et les formats légers pour un impact écologique minimal et une autonomie locale maximale.",
  about_val3_title_fr: "Égalité des chances & mixité",
  about_val3_desc_fr: "Encourager prioritairement l'autonomisation des jeunes filles et des femmes à travers des programmes dédiés pour faire tomber les barrières de genre.",
  about_val4_title_fr: "Souveraineté & culture libre",
  about_val4_desc_fr: "Promouvoir les logiciels libres, l'Open Data et le partage horizontal des connaissances contre toute forme de dépendance technologique.",
  about_val5_title_fr: "Intégrité & transparence",
  about_val5_desc_fr: "Une gouvernance rigoureuse, des comptes vérifiés et des bilans d'activités publics garantissant une relation de confiance absolue.",
  about_gov_eyebrow_fr: "ORGANISATION",
  about_gov_title_fr: "Gouvernance & Structure",
  about_gov_subtitle_fr: "Une gouvernance collégiale, démocratique et ancrée dans le respect des statuts associatifs togolais.",
  about_gov1_role_fr: "Instance souveraine d'orientation",
  about_gov1_title_fr: "Assemblée Générale",
  about_gov1_desc_fr: "Réunit chaque année l'ensemble des membres adhérents pour approuver les rapports moraux, financiers et fixer les grandes orientations stratégiques.",
  about_gov2_role_fr: "Pilotage opérationnel & déploiement",
  about_gov2_title_fr: "Bureau Exécutif & Direction",
  about_gov2_desc_fr: "Équipe opérationnelle chargée de la mise en œuvre quotidienne des programmes, de la gestion administrative, financière et de la coordination des volontaires.",
  about_gov3_role_fr: "Garant d'impact & ancrage local",
  about_gov3_title_fr: "Comité Consultatif Communautaire",
  about_gov3_desc_fr: "Composé de représentants des villageois d'Agbélouvé, d'enseignants et d'artisans, veillant à la pertinence sociale et culturelle des actions menées.",
  about_cta_eyebrow_fr: "ENGAGEMENT",
  about_cta_title_fr: "PARTICIPEZ À L'AVENTURE APTIC-R",
  about_cta_subtitle_fr: "Vous souhaitez rejoindre la communauté, devenir volontaire de terrain ou construire un partenariat institutionnel ?",
  about_cta_btn_member_fr: "Devenir membre",
  about_cta_btn_volunteer_fr: "Devenir volontaire",
  about_cta_btn_partner_fr: "Devenir partenaire",

  // ── ENGLISH (100% complet) ──
  about_eyebrow_en: "ABOUT APTIC-R",
  about_title_en: "Building lasting digital bridges\nin the heart of rural Africa.",
  about_subtitle_en: "Since its founding in Agbélouvé, APTIC-R has been dedicated to ensuring that the digital and technological revolution leaves no village, no woman, and no young person behind.",
  about_story_eyebrow_en: "OUR STORY",
  about_story_headline_en: "A grassroots initiative created to bridge the rural digital divide.",
  about_story_p1_en: "In 2018, in the rural canton of Agbélouvé (Zio Prefecture, Togo), an urgent reality became apparent: while the world was accelerating into artificial intelligence and high-tech connectivity, village communities remained deprived of computing facilities, reliable internet, and adapted vocational tech training.",
  about_story_p2_en: "To prevent growing spatial inequality and youth disenfranchisement, a collective of Togolese engineers, educators, and community organizers decided to take action. Thus, APTIC-R (Association for the Promotion of ICT in Rural Areas) was founded.",
  about_story_p3_en: "By establishing grassroots learning labs powered by solar energy and refurbished hardware, APTIC-R turned Agbélouvé into a living laboratory for frugal innovation, youth empowerment, and connected craft.",
  about_story_image_alt_en: "APTIC-R fieldwork in Agbélouvé, community digital literacy training workshop",
  about_story_location_tag_en: "Community Roots",
  about_story_location_en: "Agbélouvé, Maritime Region, Togo",
  about_step1_label_en: "Founded in Agbélouvé",
  about_step2_label_en: "Official Registration",
  about_step3_year_en: "Today",
  about_step3_label_en: "Growth & Impact",
  about_pillars_eyebrow_en: "STRATEGIC FRAMEWORK",
  about_pillars_title_en: "Mission, Vision & Philosophy",
  about_mission_title_en: "OUR MISSION",
  about_mission_desc_en: "Democratize digital education and useful technology in rural and peri-urban areas through hands-on training, community experimentation, and sustainable skill transfer.",
  about_vision_title_en: "OUR VISION",
  about_vision_desc_en: "An empowered rural community where open-source technology and low-tech tools bolster local food sovereignty, economic resilience, and civic engagement.",
  about_philosophy_title_en: "OUR PHILOSOPHY",
  about_philosophy_desc_en: "Frugal, adapted technology. We reject tech for tech's sake: every tool we deploy must be locally repairable, energy-efficient, accessible, and directly beneficial to the village.",
  about_stat1_lbl_en: "Years of grassroots action",
  about_stat2_lbl_en: "Youth, students & artisans trained",
  about_stat3_lbl_en: "Partner schools & institutions",
  about_stat4_lbl_en: "Locally co-designed projects",
  about_values_eyebrow_en: "CORE PRINCIPLES",
  about_values_title_en: "Our 5 core values",
  about_values_subtitle_en: "Guiding principles driving every initiative and partnership.",
  about_val1_title_en: "Community Roots",
  about_val1_desc_en: "Nothing is undertaken without the full involvement, consent, and co-ownership of traditional leaders, grassroots groups, and local families.",
  about_val2_title_en: "Digital Frugality & Low-Tech",
  about_val2_desc_en: "Prioritizing refurbished hardware, solar energy, simple sensors, and lightweight formats for minimal ecological footprint and maximum local autonomy.",
  about_val3_title_en: "Equal Opportunity & Inclusion",
  about_val3_desc_en: "Actively fostering women's empowerment through tailored programs to break down gender barriers in science and technology.",
  about_val4_title_en: "Sovereignty & Open Culture",
  about_val4_desc_en: "Promoting free/open-source software, Open Data, and horizontal knowledge sharing against all forms of technological dependency.",
  about_val5_title_en: "Integrity & Transparency",
  about_val5_desc_en: "Strict management, audited records, and public activity reports maintaining full trust among members, partners, and beneficiaries.",
  about_gov_eyebrow_en: "ORGANIZATION",
  about_gov_title_en: "Governance & Structure",
  about_gov_subtitle_en: "Democratic, collaborative governance anchored in non-profit transparency.",
  about_gov1_role_en: "Sovereign policy-setting body",
  about_gov1_title_en: "General Assembly",
  about_gov1_desc_en: "Sovereign annual gathering of all members to review moral and financial reports and chart future strategic milestones.",
  about_gov2_role_en: "Operational leadership & delivery",
  about_gov2_title_en: "Executive Board & Management",
  about_gov2_desc_en: "Operational team responsible for program implementation, administrative oversight, volunteer safety, and daily coordination.",
  about_gov3_role_en: "Community relevance & local anchor",
  about_gov3_title_en: "Community Advisory Board",
  about_gov3_desc_en: "Comprising Agbélouvé elders, teachers, and local artisans ensuring relevance, cultural alignment, and genuine community benefit.",
  about_cta_eyebrow_en: "GET INVOLVED",
  about_cta_title_en: "JOIN THE APTIC-R ADVENTURE",
  about_cta_subtitle_en: "Whether you want to join our membership community, volunteer in the field, or build an institutional partnership, we welcome you.",
  about_cta_btn_member_en: "Become a member",
  about_cta_btn_volunteer_en: "Become a volunteer",
  about_cta_btn_partner_en: "Become a partner",

  // ── DEUTSCH (100% complet) ──
  about_eyebrow_de: "ÜBER APTIC-R",
  about_title_de: "Nachhaltige digitale Brücken\nim ländlichen Raum bauen.",
  about_subtitle_de: "Seit der Gründung in Agbélouvé setzt sich APTIC-R dafür ein, dass die technologische Revolution kein Dorf, keine Frau und keinen jungen Menschen zurücklässt.",
  about_story_eyebrow_de: "UNSERE GESCHICHTE",
  about_story_headline_de: "Eine Initiative aus der Praxis, um die digitale Kluft auf dem Land zu überwinden.",
  about_story_p1_de: "Im Jahr 2018 wurde im ländlichen Agbélouvé (Präfektur Zio, Togo) eine dringliche Realität sichtbar: Während die Welt in rasantem Tempo voranschreitet, blieben Dorfgemeinschaften von IT-Infrastruktur, stabiler Verbindung und Ausbildung abgeschnitten.",
  about_story_p2_de: "Um dieser Chancenungleichheit und Abwanderung entgegenzuwirken, schloss sich ein Kollektiv togoischer Ingenieure, Pädagogen und Gemeindemitglieder zusammen und gründete APTIC-R.",
  about_story_p3_de: "Mit solarbetriebenen Lernwerkstätten und wiederaufbereiteten Computern wurde Agbélouvé zu einem lebendigen Reallabor für ländliche Innovation, Jugendförderung und vernetztes Handwerk.",
  about_story_image_alt_de: "APTIC-R Feldarbeit in Agbélouvé, gemeinschaftliche digitale Bildungsinitiative",
  about_story_location_tag_de: "Gemeinschaftsverankerung",
  about_story_location_de: "Agbélouvé, Region Maritime, Togo",
  about_step1_label_de: "Gründung in Agbélouvé",
  about_step2_label_de: "Offizielle Registrierung",
  about_step3_year_de: "Heute",
  about_step3_label_de: "Wachstum & Wirkung",
  about_pillars_eyebrow_de: "STRATEGISCHER RAHMEN",
  about_pillars_title_de: "Mission, Vision & Philosophie",
  about_mission_title_de: "UNSERE MISSION",
  about_mission_desc_de: "Demokratisierung digitaler Bildung im ländlichen Raum durch praxisnahe Schulungen, Reallabore und nachhaltigen Kompetenztransfer.",
  about_vision_title_de: "UNSERE VISION",
  about_vision_desc_de: "Selbstbestimmte ländliche Gemeinschaften, in denen freie Technologie und Low-Tech die lokale Ernährungs-, Wirtschafts- und Bildungssouveränität stärken.",
  about_philosophy_title_de: "UNSERE PHILOSOPHIE",
  about_philosophy_desc_de: "Sparsame, angepasste Technologie. Jedes Werkzeug muss lokal reparierbar, energieeffizient, zugänglich und unmittelbar nützlich sein.",
  about_stat1_lbl_de: "Jahre Engagement vor Ort",
  about_stat2_lbl_de: "Ausgebildete Jugendliche & Handwerker",
  about_stat3_lbl_de: "Partnerschulen & Institutionen",
  about_stat4_lbl_de: "Lokal mitgestaltete Projekte",
  about_values_eyebrow_de: "GRUNDPRINZIPIEN",
  about_values_title_de: "Unsere 5 Grundwerte",
  about_values_subtitle_de: "Feste Leitprinzipien für unser tägliches Handeln vor Ort.",
  about_val1_title_de: "Gemeinschaftsverankerung",
  about_val1_desc_de: "Enge Zusammenarbeit mit Dorfoberhäuptern, Basisgruppen und Familien vor Ort.",
  about_val2_title_de: "Low-Tech & Nachhaltigkeit",
  about_val2_desc_de: "Priorisierung von Solarenergie und wiederaufbereiteter Hardware für maximale Autonomie.",
  about_val3_title_de: "Chancengleichheit & Inklusion",
  about_val3_desc_de: "Gezielte Förderung von jungen Frauen in MINT-Fächern zur Überwindung von Hürden.",
  about_val4_title_de: "Freies Wissen & Open Source",
  about_val4_desc_de: "Förderung freier Software und Open Data gegen technologische Abhängigkeiten.",
  about_val5_title_de: "Integrität & Transparenz",
  about_val5_desc_de: "Sorgfältige Finanzführung und öffentlich zugängliche Jahresberichte für volles Vertrauen.",
  about_gov_eyebrow_de: "ORGANISATION",
  about_gov_title_de: "Governance & Struktur",
  about_gov_subtitle_de: "Demokratische und transparente Vereinsführung nach togoischem Verbandsstatut.",
  about_gov1_role_de: "Souveränes Beschlussorgan",
  about_gov1_title_de: "Generalversammlung",
  about_gov1_desc_de: "Jährliches Treffen aller Mitglieder zur Genehmigung der Berichte und strategischen Leitlinien.",
  about_gov2_role_de: "Operative Umsetzung & Steuerung",
  about_gov2_title_de: "Vorstand & Leitung",
  about_gov2_desc_de: "Operatives Team zur Durchführung von Programmen und Betreuung von Freiwilligen vor Ort.",
  about_gov3_role_de: "Lokale Wirkung & Dialog",
  about_gov3_title_de: "Gemeindebeirat",
  about_gov3_desc_de: "Zusammenschluss von Dorfvertretern, Lehrern und Handwerkern zur Qualitätssicherung vor Ort.",
  about_cta_eyebrow_de: "MITWIRKEN",
  about_cta_title_de: "WERDEN SIE TEIL DER INITIATIVE",
  about_cta_subtitle_de: "Ob Mitglied werden, vor Ort als Freiwilliger aktiv sein oder eine Partnerschaft aufbauen — Ihre Unterstützung zählt.",
  about_cta_btn_member_de: "Mitglied werden",
  about_cta_btn_volunteer_de: "Freiwilliger werden",
  about_cta_btn_partner_de: "Partner werden",
}
