export type Page =
  | "home"
  | "apply"
  | "partner"
  | "admin-login"
  | "admin-dashboard"
  | "admin-applications"
  | "admin-candidate"
  | "admin-candidates"
  | "admin-analytics"
  | "admin-partner-requests"
  | "admin-partner-request-detail"
  | "admin-partners"

export type Language = "FR" | "EN" | "DE"
